### ISSUE TITLE
Loading JSONs with URIs and labels

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-web-tagger#2]
The system should support loading of JSON files holding URIs and Labels that will be used during the tagging process.

Each JSON has objects with the following attributes:
{"uri" : "text:tanach-1-1-1", "text" : "בראשית ברא אלהים את השמים ואת הארץ",
"labels" : [ {"label"  : "בראשית א א"}, {"label" : "בראשית פרק א פסוק א"}]}

The system should provide feedback about the loading process, e.g., how many objects were loaded, objects that were ignored, etc.

Notes:
- Instead of using explicit urls for the tags, we use prefixes (e.g., "text:"). This means that we will not have in the entire system explicit URIs.

**Comment by lchayoun** [comment]
support was added during initial project development
