### ISSUE TITLE
Auto-completion stopped working after last update

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-web-tagger#21]
Hi, just pulled the code after the URI text-field was changed to "float" (task #18) and noticed that the auto completion of URIs is not functioning. Please fix a.s.a.p since we can't tag any texts.

The tool is available at http://tdk-p6.cs.technion.ac.il:8000/. Example input may be found at #18.

@TechnionTDK/team-jbs-web-tagger

**Comment by lchayoun** [comment]
Hi Oren, this happened because we ran on remove host and "localhost" was
used to get the data (uri jsons).

This is not related to the latest change.
Please pull the code and verify that it is running ok now,

Liel

**Comment by omishali** [comment]
It is OK now, thanks!

2016-12-20 23:13 GMT+02:00 lchayoun <notifications@github.com>:
