### ISSUE TITLE
Problem with tagging two parts books

### ISSUE THREAD

**Issue by moshesab** [TechnionTDK/jbs-web-tagger#24]
Hi, 
It seems like you didn't allow to tag books which divided to two parts in right way. For example there are no מלכים א and מלכים ב but just מלכים. Same in דברי הימים, שמואל etc.

@omishali  @TechnionTDK/team-jbs-web-tagger

**Comment by omishali** [comment]
Hi Moshe,
It is not their problem but the problem of the text2json team that produces
the jbs-text repo. Please add an issue in the repo of text2json.
Thanks!

2016-12-22 15:39 GMT+02:00 moshesab <notifications@github.com>:

**Comment by lchayoun** [comment]
this ticket was moved to TechnionTDK/jbs-text2json#27
