### ISSUE TITLE
Problem with openning json files after editting them with the web-tagger

### ISSUE THREAD

**Issue by moshesab** [TechnionTDK/jbs-web-tagger#25]
Hi, 
I made some tagged json files with the web-tagger but after I tried to open the new tagged json files I got an error that the file is coruppted "cannot read property '$hashKey$' of undifined". 
The wired thing is that it open the files before I tag them successfully.

@omishali  @TechnionTDK/team-jbs-web-tagger

**Comment by lchayoun** [comment]
@moshesab please attach the json, we can't understand the root cause of the issue without having the file

**Comment by moshesab** [comment]
[oren (4).json.txt](https://github.com/TechnionTDK/jbs-web-tagger/files/669579/oren.4.json.txt)

Here is the file. Please notice you take off the ".txt".  The file was made by the web tagger

**Comment by moshesab** [comment]
@lchayoun  @EylonSho

**Comment by lchayoun** [comment]
@omishali This is working with the latest fix, please update the site

**Comment by omishali** [comment]
Done, thanks.

2016-12-22 20:59 GMT+02:00 lchayoun <notifications@github.com>:
