### ISSUE TITLE
Add/Remove/Update tag

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-web-tagger#3]
The user can attach tags to a **span** within a text (a span is a sequence of words). For example, he can mark some words and ask for adding a tag. Most of the time, the user may be interested in adding a single tag, however sometimes several tags should be added for the same span.

To specify the tag, the user will provide the textual label or part of it, then the candidate URIs will be presented and the user will choose one.

**Comment by lchayoun** [comment]
support was added during initial project development
