### ISSUE TITLE
Changes in json format

### ISSUE THREAD

**Issue by omishali** [TechnionTDK/jbs-web-tagger#30]
There are two small changes that were made in the jsons and should be reflected in the system. Please try to implement them a.s.a.p.

1. **In the JSON of the URIs.** Currently you are looking for "titles" array that holds the labels. Continue to support the "titles" array but first look for "rdfs:label" attribute (e.g., "rdfs:label" : "בראשית א א"). If that attribute exists, then take the label from there. If not, search for the "titles" array. Note that the "titles" array may not exist at all.
2. **In the JSON of the text to be tagged**. Currently you are looking for a "text" attribute that holds the text to be tagged. The attribute was changed to "jbo:text".

**Comment by lchayoun** [comment]
@omishali please check and update if something is still not working

**Comment by omishali** [comment]
Thanks! I will check tomorrow morning.

בתאריך 20 בינו׳ 2017 1:26 אחה״צ,‏ "lchayoun" <notifications@github.com> כתב:

**Comment by omishali** [comment]
I did the following:
* Replaced the jsons in app/data and restarted the server.
* Tried to upload a file for tagging (https://github.com/TechnionTDK/jbs-text/tree/master/seferhamitzvot).

Then I got the following error. Note that the file doesn't have the field "titles" at all. Instead it has the field "rdfs:label".

![error](https://cloud.githubusercontent.com/assets/3026479/22181832/868504de-e09d-11e6-8533-6fc924fbae76.JPG)

**Comment by lchayoun** [comment]
@omishali validated again now, added the missing change, please check again

**Comment by omishali** [comment]
Now the loading of the text works but I found another bug:
* I've added to app/data the file https://github.com/TechnionTDK/jbs-text/tree/master/seferhamitzvot. This file contains no "titles" array but rdfs:label attribute.
* I started the server and the URIs defined in that json were not available. Moreover, also the URIs of the tanach jsons were not available. When I deleted the seferhamitzvot.json and restarted the server, the URIs of the tanach jsons were made available again.

Currently, seferhamitzvot.json is not within app/data.

**Comment by lchayoun** [comment]
![image](https://cloud.githubusercontent.com/assets/10900826/22183446/2053f8ee-e0c7-11e6-8846-2a4bbfa290c6.png)
 @omishali added support for rdfs:label in database files as well

**Comment by omishali** [comment]
It is getting improved but still has problems...
Now when I type e.g. "בראשית א א" the labels appears twice in each
available option:
[image: תמונה מוטבעת 1]

2017-01-22 17:21 GMT+02:00 lchayoun <notifications@github.com>:

**Comment by lchayoun** [comment]
@omishali this is happening because both rdfs:label and titles exist? added a fix for this case.

**Comment by omishali** [comment]
Indeed that was the case. Now it works fine. Note that in case that both
rdfs:label and titles exist you should ignore titles.

2017-01-22 22:58 GMT+02:00 lchayoun <notifications@github.com>:
